config/routes.rb
Rails.application.routes.draw do

  resources :answers  , only: [:create, :destroy]

  resources :questions, only: [:create, :destroy]
  root to: "home#index"
  get 'home/index'
  get '/profile' => 'home#profile'
  post '/upload' => 'home#upload_image'
  

  devise_for :users
  post '/toggle' => 'upvote#toggle_upvote'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question , dependent: :destroy
  validates :content, presence: true 

  def upvote_by user_id
  	Upvote.where(qa_id: id, user_id: user_id, utype: 'answer').length > 0
  end


  def upvote_string user_id
  	if upvote_by user_id
  		return "Cancel Upvote"
  	else
  		return "Upvote"
  	end

  end

  def upvote_count

  	return Upvote.where(qa_id: id , utype: 'answer').length

  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :content, presence: true 

  def upvote_by user_id
  	Upvote.where(qa_id: id, user_id: user_id, utype: 'question').length > 0
  end


  def upvote_string user_id
  	if upvote_by user_id
  		return "Cancel Upvote"
  	else
  		return "Upvote"
  	end

  end

  def upvote_count

  	return Upvote.where(qa_id: id , utype: 'question').length

  end	
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :confirmable

  enum role: {reader:0 , member: 1, moderator: 2, admin: 3}      

 
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end


  def create
    @answer = Answer.new(answer_params)
    respond_to do |format|
      if @answer.save
        format.html { redirect_to '/', notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
        format.js{}
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js{}
        
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content, :user_id, :question_id )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController	
  def index
   	if current_user==nil && Question.all.length == 0 
   		return redirect_to new_user_session_path
  	else
  	@question= Question.new
  	@questions=Question.all.order(created_at: :desc)
  	@answer= Answer.new
 	end
  end

  
  def profile
  end


  def upload_image
  	uploaded_file = params[:image]
  	filename = SecureRandom.hex + "." +uploaded_file.original_filename.split('.')[1]
  	filepath = Dir.pwd + "/public/uploads/" + filename
	File.open(filepath,'wb') do |file|
		file.write(uploaded_file.read())
	end

	current_user.profile_picture = filename
	current_user.save!
  	return redirect_to '/profile'
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    respond_to do |format|

      if @question.save
        format.html { redirect_to '/', notice: 'Tweet was successfully created.' }
        format.js{}
        format.json { render :show, status: :created, location: @question }

      else
        format.html { render :new }
        format.js{}
        format.json { render json: @question.errors, status: :unprocessable_entity }
        
      end
    end
  end
  

  # # PATCH/PUT /questions/1
  # # PATCH/PUT /questions/1.json
  # def update
  #   respond_to do |format|
  #     if @question.update(question_params)
  #       format.html { redirect_to @question, notice: 'Question was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @question }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @question.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :user_id)
    end
end

app/controllers/upvote_controller.rb
class UpvoteController < ApplicationController
	before_action :authenticate_user!


	def toggle_upvote
		@utype=params[:utype]
		@qa_id=params[:qa_id]
		if @utype == "question"
			@question = Question.find(params[:qa_id])
			upvote = Upvote.where(user_id: current_user.id , qa_id: @qa_id, utype: 'question').first
			if upvote
				upvote.destroy!
				@is_upvote = false	

			else
				Upvote.create(user_id: current_user.id, qa_id: @qa_id , utype: 'question')
				@is_upvote = true
			end
		else
			@answer = Answer.find(params[:qa_id])
			upvote = Upvote.where(user_id: current_user.id , qa_id: @qa_id , utype: 'answer').first
			if upvote
				upvote.destroy!
				@is_upvote = false	
			else
				Upvote.create(user_id: current_user.id, qa_id: @qa_id , utype: 'answer')
				@is_upvote = true
			end
		end	

				
		respond_to do |format|
			format.js {}
		end
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/upvote_helper.rb
module UpvoteHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.text_field :question_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.any? %>
noty({text: "<%= @answer.errors.full_messages.first %>" , type: 'error' , timeout: 1000});
<% else %>
$('#answers_<%=@answer.question.id%>').removeClass('blankans');
noty({text: 'Answer was Created succesfully', type: 'success' , timeout: 1000});
$('#answers_<%=@answer.question.id%>').prepend("<%= escape_javascript (render 'home/answer', ans: @answer) %>");
$('#answer_content_<%=@answer.question.id%>').val("");
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <td><%= answer.user %></td>
        <td><%= answer.question %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/home/_answer.html.erb
<div class="answer">
	<div class="answerpart">
			<div class="left">
				<div class="userImage">
				<% if ans.user.profile_picture %>
				<img src="/uploads/<%=ans.user.profile_picture %>">
				<% end %>
				</div>
			</div>

			<div class="right">
				<div class="userDetail">
					<%= ans.user.email %>
				</div>
				<div class="content">
					<strong><%= ans.content %></strong>
				</div>
				<br>
				<% if user_signed_in? %>

				<div class="actions"> 
				<%= link_to ans.upvote_string(current_user.id), url_for(controller: 'upvote', action: 'toggle_upvote', qa_id: ans.id , utype: 'answer') , method: :post , id: "upvote_answer_#{ans.id}" , remote: true %> 
				</div>
				<div class="count" id= "count_answer_<%= ans.id %>">
				<%= ans.upvote_count %>
				</div>
				<% end %>
			</div>	
	</div>
</div>
<br>

app/views/home/_question.html.erb
<div class="question">
	<div class="questionPart">
		<div class="left">	
			<div class="userImage">
				<% if question.user.profile_picture %>
				<img src="/uploads/<%=question.user.profile_picture %>">
				<% end %>
			</div>
		</div>

		<div class="right">
			<div class="userDetail"> 
				<%= question.user.email %>
			</div>
			<div class="content">
			<strong><%= question.content %></strong>
			</div>
			<br>
			<% if user_signed_in? %>
				<div class="actions"> 
				<%= link_to question.upvote_string(current_user.id), url_for(controller: 'upvote', action: 'toggle_upvote', qa_id: question.id , utype: 'question',) , method: :post, id: "upvote_question_#{question.id}" ,remote: true %> 
				</div>
				<div class="count" id= "count_question_<%= question.id %>">
			 	<%= question.upvote_count %>
				</div>
			<% end %>	
		</div>
		<% if question.user == current_user %>
		<div class ="dropIcon" id="dropIcon_question_<%= question.id %>">
			<div class= "onlyIcon">
				<i class="fa fa-ellipsis-h" aria-hidden="true"></i>
			</div>
			<div class="menu">

			</div>
		</div>
		<%end%>

	</div>	
	<div class="answerPart">
	<% if user_signed_in? %>
	<% @answer= Answer.new %>
		<%= form_for @answer ,remote: true do |f| %>

		<%= f.label :Your_Answer %> <br>	
		<%= f.hidden_field :question_id , :value => question.id %>
		<%= f.hidden_field :user_id , :value => current_user.id %>
		<%= f.text_area :content , :id => "answer_content_#{question.id}" %>  <br>

		<%= f.submit  %>
		<% end %>
	<% end %>
		<br>
		<% if question.answers.length == 0 %>
			<div class="answers blankans" id="answers_<%= question.id %>">
				<% question.answers.order(created_at: :desc).each do |ans| %>
				<%= render 'answer', ans: ans %>
			<% end %>
			</div>
		<%else%>
			<div class="answers" id="answers_<%= question.id %>">
				<% question.answers.order(created_at: :desc).each do |ans| %>
				<%= render 'answer', ans: ans %>
			<% end %>
			</div>
		<%end%>
	</div>
</div>
<br>

app/views/home/index.html.erb
<br>
<br>
<br>
<br>

<main>


<aside>

</aside>

<section>
<% if user_signed_in? %>
<div class="createQuestion">

<%= form_for @question ,remote: true do |f| %>

<%= f.label :Have_something_in_mind? %> <br>

<%= f.text_area :content , placeholder: 'ask a question'  %>  <br>

<%= f.submit  id: 'create_tweet_submit' , value: 'Ask' %>

<% end %>
<br>

 <% if @question.errors.any? %>
      
      <% @question.errors.full_messages.each do |message| %>
      

      <script type="text/javascript">
	noty({text: '<%= message %>', type: 'error'});
</script>
 
  <% end %>
     
  <% end %>

 </div>
 
 <% end %>



 <div id="questions">

<%  @questions.each do |question| %>

<%= render 'question', question: question %>

<% end %>

</div> 

app/views/home/profile.html.erb
<br>
<br>

<br>

<br>

<% if current_user.profile_picture %>


<img src="/uploads/<%= current_user.profile_picture %>" >

<% end %>


<%= form_tag url_for(controller: :home, action: :upload_image), multipart: true do %>


<%= file_field_tag :image %>
<br>
<%= submit_tag %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quora</title>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"> 
</script>
<% if notice %> 
<script type="text/javascript"> 
	noty({text: '<%= notice %>', type: 'alert' , timeout: 1000});
</script>

<% end %>


<% if alert %>

<script type="text/javascript">
	noty({text: '<%= alert %>', type: 'error', timeout: 1000 });
</script>
<% end %>

<header>

<div class="logo">
<%= link_to image_tag("quora.png"), home_index_path %>
</div>

<% if user_signed_in? %>
<nav class ="signedIn">

<ul >
<li> <i class="fa fa-book" aria-hidden="true"></i><%= link_to "Read",home_index_path , method: :get%></li>
<li>  <%= link_to "Profile", controller: "home" , action: "profile" %></li>
<li>  <%= link_to "Sign Out",destroy_user_session_path,method: :delete %></li>

</ul>
</nav> 

<% else %>
<nav class="signedOut">
<ul >

<li> <i class="fa fa-book" aria-hidden="true"></i><%= link_to "Read",home_index_path , method: :get%></li>
<li>  <%= link_to "Sign In",new_user_session_path , method: :get%></li>
<li>  <%= link_to "Sign Up",new_user_registration_path , method: :get%></li>

</ul>
</nav>
<%end%>


</header>

<%= yield %>

</body>
</html>
<script src="https://use.fontawesome.com/25dead7180.js"></script>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/create.js.erb
<% if @question.errors.any? %>
noty({text: "<%= @question.errors.full_messages.first %>" , type: 'error' , timeout: 1000});
<% else %>
noty({text: 'Question was Created succesfully', type: 'success' , timeout: 1000});
$('#questions').prepend("<%= escape_javascript (render 'home/question', question: @question) %>");
$('#question_content').val("");
<% end %>	

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= question.user %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @question.user %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/upvote/toggle_upvote.js.erb
<% if @utype == "question" %>
	<% if @is_upvote %>
	$('#upvote_question_<%= @qa_id%>').html("Cancel Upvote");
	noty({text: 'Question was Upvoted', type: 'alert', timeout: 1000});
	$('#count_question_<%= @qa_id%>').html("<%= @question.upvote_count %>");

	<% else %>

	$('#upvote_question_<%= @qa_id%>').html("Upvote");
	noty({text: 'Upvote cancelled', type: 'alert' , timeout: 1000});
	$('#count_question_<%= @qa_id%>').html("<%= @question.upvote_count %>");

	<% end %>
<% else %>
	<% if @is_upvote %>
	$('#upvote_answer_<%= @qa_id%>').html("Cancel Upvote");
	noty({text: 'Answer was Upvoted', type: 'alert' , timeout: 1000});
	$('#count_answer_<%= @qa_id%>').html("<%= @answer.upvote_count %>");

	<% else %>

	$('#upvote_answer_<%= @qa_id%>').html("Upvote");
	noty({text: 'Upvote cancelled', type: 'alert' , timeout: 1000});
	$('#count_answer_<%= @qa_id%>').html("<%= @answer.upvote_count %>");

	<% end %>
<% end %>	